<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework" Version="3.8.5" />
	<ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
  </ItemGroup>

</Project>
